/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:447dd025-1b7b-44b2-bef7-166e806b03a2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uKJ5AV5fI",
    "aws_user_pools_web_client_id": "6mtdae1cfgf702jeua8s6q31os",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7wykuqwnu5cq3m42zersprk5we.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
